services:
  velocity:
    container_name: mc_velocity
    image: itzg/bungeecord
    tty: true
    stdin_open: true
    environment:
      TYPE: VELOCITY
      VELOCITY_VERSION: latest
      MEMORY: 1G
      PLUGINS: |
        https://github.com/ViaVersion/ViaVersion/releases/download/5.3.2/ViaVersion-5.3.2.jar
        https://github.com/ViaVersion/ViaBackwards/releases/download/5.3.2/ViaBackwards-5.3.2.jar
        https://github.com/Camotoy/GeyserSkinManager/releases/download/1.7/GeyserSkinManager-Velocity.jar
        https://download.luckperms.net/1576/velocity/LuckPerms-Velocity-5.4.159.jar
        https://hangarcdn.papermc.io/plugins/ViaVersion/ViaBackwards/versions/5.3.2/PAPER/ViaBackwards-5.3.2.jar
        https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/5.3.2/PAPER/ViaVersion-5.3.2.jar
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
    volumes:
      - ./velocity:/server
    restart: always